
package pencatatangui;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class DataDosen extends javax.swing.JInternalFrame {
    
    private DefaultTableModel model;
    static ResultSet rs;
    static Statement stmt;
    DbCnn cnn = new DbCnn();
    /**
     * Creates new form DataDosen
     */
    public DataDosen() {
        initComponents();
        this.initTable();
        this.GetData();
    }
    
    private void initTable(){
        model = new DefaultTableModel();
        TabelDosen.setModel(model);
        model.addColumn("NIDN");
        model.addColumn("Nama Dosen");
        model.addColumn("No.Telepon");
        model.addColumn("Tanggal Lahir");
        model.addColumn("Jenis Kelamin");        
        model.addColumn("Pendidikan");
        model.addColumn("Status Ikatan Kerja");
    }
    
    private void ShowData(String sql){
        try{
            Statement stmt = cnn.koneksi().createStatement();
            this.rs = stmt.executeQuery(sql);
        }catch(Exception e){
            System.out.println("Terjadi Kendala pada query");
        }
    }
    private void GetData(){
        String sql = "Select nidn, nama, no_tlp, tgl_lahir, jk, pendidikan, status_ikatan FROM dosen;";
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try{
            this.ShowData(sql);
            while(this.rs.next()){
                Object[] obj = new Object[7];
                obj[0] = this.rs.getString("nidn");
                obj[1] = this.rs.getString("nama");
                obj[2] = this.rs.getString("no_tlp");
                obj[3] = this.rs.getString("tgl_lahir");
                obj[5] = this.rs.getString("pendidikan");
                obj[6] = this.rs.getString("status_ikatan");
                String txJK = this.rs.getString("jk");
                if(txJK.equals("L")){
                    obj[4] = "Laki-Laki";
                }else{
                    obj[4] = "Perempuan";
                }
                model.addRow(obj);
            }
        }catch(Exception e){
        }
    }
    
    private boolean UpdateData(String SQL){
        boolean hsl = false;
        try{
            Statement stmt = cnn.koneksi().createStatement();
            stmt.executeUpdate(SQL);
            hsl = true;
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Terjadi kendala pada instruksi SQL");
        }
        return hsl;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnAddNew = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelDosen = new javax.swing.JTable();
        LabelDetail = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Fnidn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Fnama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        FjkL = new javax.swing.JRadioButton();
        FjkP = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        Fno_tlp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Ftgl_lahir = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Fpendidikan = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        Fstatus = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        BtnUpdate = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        BtnSave = new javax.swing.JButton();
        BtnCancel = new javax.swing.JButton();
        BtnClose = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel1.setText("Tabel Data Dosen");

        BtnAddNew.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        BtnAddNew.setText("Tambah Data");
        BtnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddNewActionPerformed(evt);
            }
        });

        TabelDosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelDosenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelDosen);

        LabelDetail.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        LabelDetail.setText("Detail Profil");

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel3.setText("NIDN");

        Fnidn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel4.setText("Nama Dosen ");

        Fnama.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel5.setText("Jenis Kelamin");

        FjkL.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        FjkL.setText("Laki-laki");
        FjkL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FjkLActionPerformed(evt);
            }
        });

        FjkP.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        FjkP.setText("Perempuan");

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel6.setText("No.Telepon");

        Fno_tlp.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel7.setText("Tanggal Lahir");

        Ftgl_lahir.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel8.setText("Pendidikan");

        Fpendidikan.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Fpendidikan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Pendidikan", "S1", "S2", "S3" }));

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel9.setText("Status Ikatan Kerja");

        Fstatus.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Fstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Status", "Dosen Tetap", "Dosen Honorer", "Dosen Tidak Tetap" }));
        Fstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FstatusActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jTextPane1);

        BtnUpdate.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        BtnUpdate.setText("Update Data");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        BtnDelete.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        BtnDelete.setText("Delete Data");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        BtnSave.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        BtnSave.setText("Simpan Data");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        BtnCancel.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        BtnCancel.setText("Batal");
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });

        BtnClose.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        BtnClose.setText("Tutup Form");
        BtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnDelete)
                                .addGap(205, 205, 205))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Fnama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                    .addComponent(jLabel3)
                                    .addComponent(Fno_tlp, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Fnidn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Ftgl_lahir)
                                        .addGap(36, 36, 36)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(Fstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(91, 91, 91))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtnSave)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BtnCancel))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(Fpendidikan, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(FjkL)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(FjkP))))
                                .addGap(310, 310, 310))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BtnClose)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LabelDetail)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnAddNew)))
                        .addContainerGap(39, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(BtnAddNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelDetail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Fstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Fnidn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Ftgl_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(26, 26, 26))
                            .addComponent(Fnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FjkL)
                                    .addComponent(FjkP))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Fno_tlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Fpendidikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane2))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnUpdate)
                    .addComponent(BtnDelete)
                    .addComponent(BtnSave)
                    .addComponent(BtnCancel)
                    .addComponent(BtnClose))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FjkLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FjkLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FjkLActionPerformed

    private void FstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FstatusActionPerformed

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        String NIDN = this.Fnidn.getText();
        String NAMA = this.Fnama.getText();
        String NO_TLP = this.Fno_tlp.getText();
        String TGL_LAHIR = this.Ftgl_lahir.getText();
        String PENDIDIKAN = this.Fpendidikan.getSelectedItem().toString();
        String STATUS = this.Fstatus.getSelectedItem().toString();
        String JKEL = "L";
        if(this.FjkP.isSelected()){
            JKEL = "P";
        }
        String SQLInsert = "INSERT INTO dosen(nidn,nama,no_tlp,tgl_lahir,jk,pendidikan,status_ikatan) VALUES('"+NIDN+"','"+NAMA+"','"+NO_TLP+"','"+TGL_LAHIR+"','"+JKEL+"','"+PENDIDIKAN+"','"+STATUS+"');";
        if(this.UpdateData(SQLInsert)){
            this.GetData();
            JOptionPane.showMessageDialog(null, "Data telah di Tambahkan");
        }
        this.BtnSave.setEnabled(false);
        this.BtnCancel.setVisible(false);
        this.BtnClose.setEnabled(true);
        this.BtnAddNew.setEnabled(true);
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed
        this.BtnClose.setEnabled(true);
        this.BtnAddNew.setEnabled(true);
        this.BtnSave.setEnabled(false);
        this.BtnCancel.setVisible(false);
    }//GEN-LAST:event_BtnCancelActionPerformed

    private void BtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnCloseActionPerformed

    private void TabelDosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelDosenMouseClicked
        this.Fnidn.setText( model.getValueAt(TabelDosen.getSelectedRow(), 0).toString());
        this.Fnama.setText( model.getValueAt(TabelDosen.getSelectedRow(), 1).toString());
        this.Fno_tlp.setText( model.getValueAt(TabelDosen.getSelectedRow(), 2).toString());
        this.Ftgl_lahir.setText( model.getValueAt(TabelDosen.getSelectedRow(), 3).toString());
        this.Fpendidikan.setSelectedItem(model.getValueAt(TabelDosen.getSelectedRow(), 5).toString());
        this.Fstatus.setSelectedItem(model.getValueAt(TabelDosen.getSelectedRow(), 6).toString());
        String Fjk = model.getValueAt(TabelDosen.getSelectedRow(), 4).toString();
        if(Fjk.equals("Perempuan")){
            this.FjkP.setSelected(true);
        }else{
            this.FjkL.setSelected(true);
        }
        
        this.LabelDetail.setText("Edit Data "+this.Fnama.getText());
        this.BtnSave.setEnabled(false);
        this.BtnUpdate.setEnabled(true);
        this.BtnDelete.setEnabled(true);
    }//GEN-LAST:event_TabelDosenMouseClicked

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        String NIDN = this.Fnidn.getText();
        String NAMA = this.Fnama.getText();
        String NO_TLP = this.Fno_tlp.getText();
        String TGL_LAHIR = this.Ftgl_lahir.getText();
        String PENDIDIKAN = this.Fpendidikan.getSelectedItem().toString();        
        String STATUS = this.Fstatus.getSelectedItem().toString();
        String JKEL = "L";
        if(this.FjkP.isSelected()){
            JKEL = "P";
        }
        String SQLUpdate = "UPDATE dosen SET nama='"+NAMA+"', no_tlp='"+NO_TLP+"', jk='"+JKEL+"', tgl_lahir='"+TGL_LAHIR+"', pendidikan='"+PENDIDIKAN+"', status_ikatan='"+STATUS+"' WHERE nidn='"+NIDN+"';";
        if(this.UpdateData(SQLUpdate)){
            this.GetData();
            JOptionPane.showMessageDialog(null, "Data telah di Update");
        }
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        String NIDN = this.Fnidn.getText();
        String NAMA = this.Fnama.getText();
        
        int opsi = JOptionPane.showConfirmDialog(null,"Yakin akan menghapus data dari "+NAMA+"("+NIDN+")?","Konfirmasi", JOptionPane.YES_NO_OPTION );
        if(opsi == JOptionPane.YES_OPTION){
            String SQLDelete = "DELETE FROM dosen WHERE nidn='"+NIDN+"';";
            if(this.UpdateData(SQLDelete)){
                this.GetData();
                JOptionPane.showMessageDialog(null, "Data telah dihapus");
            }
        }
        this.BtnAddNew.setEnabled(true);
        this.BtnClose.setEnabled(true);
        this.BtnCancel.setVisible(false);
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void BtnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddNewActionPerformed
        this.BtnAddNew.setEnabled(false);
        this.BtnUpdate.setEnabled(false);
        this.BtnDelete.setEnabled(false);
        this.BtnClose.setEnabled(false);
        this.BtnSave.setEnabled(true);
        this.BtnCancel.setVisible(true);
        
        this.Fnidn.setText("");
        this.Fnama.setText("");
        this.Fno_tlp.setText("");
        this.Ftgl_lahir.setText("");
        this.Fpendidikan.setSelectedIndex(0);
        this.Fstatus.setSelectedIndex(0);

        
        this.LabelDetail.setText("Tambah data Dosen");
    }//GEN-LAST:event_BtnAddNewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddNew;
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnClose;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnSave;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JRadioButton FjkL;
    private javax.swing.JRadioButton FjkP;
    private javax.swing.JTextField Fnama;
    private javax.swing.JTextField Fnidn;
    private javax.swing.JTextField Fno_tlp;
    private javax.swing.JComboBox<String> Fpendidikan;
    private javax.swing.JComboBox<String> Fstatus;
    private javax.swing.JTextField Ftgl_lahir;
    private javax.swing.JLabel LabelDetail;
    private javax.swing.JTable TabelDosen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
