package pencatatangui;

import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class DataMhs extends javax.swing.JInternalFrame {
    private DefaultTableModel model;
    static ResultSet rs;
    static Statement stmt;
    DbCnn cnn = new DbCnn();
    
    /**
     * Creates new form DataMhs
     */
    public DataMhs() {
        initComponents();
        this.InitTable();
        this.GetData();
        this.BtnCancel.setVisible(false);
    }
    
    private void InitTable(){
        model = new DefaultTableModel();
        TabelMahasiswa.setModel(model);
        model.addColumn("NIM");
        model.addColumn("Nama Mahasiswa");
        model.addColumn("Tgl Lahir");
        model.addColumn("Jurusan");
        model.addColumn("Jenis Kelamin");
    }
    private void ShowData(String sql){
        try{
            Statement stmt = cnn.koneksi().createStatement();
            this.rs = stmt.executeQuery(sql);
        }catch(Exception e){
            System.out.println("Terjadi Kendala pada query");
        }
    }
    private void GetData(){
        String sql = "Select nim, nama, tanggal_lahir, jurusan, jk FROM mahasiswa;";
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try{
            this.ShowData(sql);
            while(this.rs.next()){
                Object[] obj = new Object[5];
                obj[0] = this.rs.getString("nim");
                obj[1] = this.rs.getString("nama");
                obj[2] = this.rs.getString("tanggal_lahir");
                obj[3] = this.rs.getString("jurusan");
                String txJK = this.rs.getString("jk");
                if(txJK.equals("L")){
                    obj[4] = "Laki-Laki";
                }else{
                    obj[4] = "Perempuan";
                }
                model.addRow(obj);
            }
        }catch(Exception e){
        }
    }
    private boolean UpdateData(String SQL){
        boolean hsl = false;
        try{
            Statement stmt = cnn.koneksi().createStatement();
            stmt.executeUpdate(SQL);
            hsl = true;
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Terjadi kendala pada instruksi SQL");
        }
        return hsl;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        BtnAddNew = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelMahasiswa = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        LabelDetail = new javax.swing.JLabel();
        Fnim = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Fnama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ftgl_lahir = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        FjkL = new javax.swing.JRadioButton();
        FjkP = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        Fjurusan = new javax.swing.JComboBox<>();
        BtnSave = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        BtnCancel = new javax.swing.JButton();
        BtnClose = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel1.setText("Tabel Data Mahasiswa");

        BtnAddNew.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        BtnAddNew.setText("Tambah Data");
        BtnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddNewActionPerformed(evt);
            }
        });

        TabelMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelMahasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelMahasiswa);

        LabelDetail.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        LabelDetail.setText("Detail Profil");

        Fnim.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel4.setText("NIM");

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel5.setText("Nama Mahasiswa");

        Fnama.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel6.setText("Tgl Lahir");

        ftgl_lahir.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel7.setText("Jenis Kelamin");

        buttonGroup1.add(FjkL);
        FjkL.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        FjkL.setText("Laki-Laki");

        buttonGroup1.add(FjkP);
        FjkP.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        FjkP.setText("Perempuan");

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel8.setText("Jurusan");

        Fjurusan.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Fjurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jurusan", "MTI", "SK", "KAB" }));

        BtnSave.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        BtnSave.setText("Simpan Data");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        BtnUpdate.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        BtnUpdate.setText("Update Data");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        BtnDelete.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        BtnDelete.setText("Hapus Data");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        BtnCancel.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        BtnCancel.setText("Batal");
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });

        BtnClose.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        BtnClose.setText("Tutup Form");
        BtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCloseActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(Fnim, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(ftgl_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(Fnama, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(FjkL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(FjkP))
                                    .addComponent(jLabel8)
                                    .addComponent(Fjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(LabelDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(BtnDelete)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(516, 516, 516)
                                .addComponent(BtnSave)
                                .addGap(18, 18, 18)
                                .addComponent(BtnCancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                                .addComponent(BtnClose)))
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(BtnAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelDetail)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6))
                                    .addGap(11, 11, 11)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Fnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ftgl_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Fnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(FjkL)
                                        .addComponent(FjkP))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Fjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSave)
                    .addComponent(BtnUpdate)
                    .addComponent(BtnDelete)
                    .addComponent(BtnCancel)
                    .addComponent(BtnClose))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnCloseActionPerformed

    private void TabelMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelMahasiswaMouseClicked
        this.Fnim.setText( model.getValueAt(TabelMahasiswa.getSelectedRow(), 0).toString());
        this.Fnama.setText( model.getValueAt(TabelMahasiswa.getSelectedRow(), 1).toString());
        this.ftgl_lahir.setText( model.getValueAt(TabelMahasiswa.getSelectedRow(), 2).toString());
        this.Fjurusan.setSelectedItem(model.getValueAt(TabelMahasiswa.getSelectedRow(), 3).toString());
        String txJK = model.getValueAt(TabelMahasiswa.getSelectedRow(), 4).toString();
        if(txJK.equals("Perempuan")){
            this.FjkP.setSelected(true);
        }else{
            this.FjkL.setSelected(true);
        }
        
        this.LabelDetail.setText("Edit Data "+this.Fnama.getText());
        this.BtnSave.setEnabled(false);
        this.BtnUpdate.setEnabled(true);
        this.BtnDelete.setEnabled(true);
    }//GEN-LAST:event_TabelMahasiswaMouseClicked

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        String NIM = this.Fnim.getText();
        String NAMA = this.Fnama.getText();
        String TGL = this.ftgl_lahir.getText();
        String JUR = this.Fjurusan.getSelectedItem().toString();
        String JKEL = "L";
        if(this.FjkP.isSelected()){
            JKEL = "P";
        }
        String SQLUpdate = "UPDATE mahasiswa SET nama='"+NAMA+"', jurusan='"+JUR+"', jk='"+JKEL+"', tanggal_lahir='"+TGL+"' WHERE nim='"+NIM+"';";
        if(this.UpdateData(SQLUpdate)){
            this.GetData();
            JOptionPane.showMessageDialog(null, "Data telah di Update");
        }
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        String NIM = this.Fnim.getText();
        String NAMA = this.Fnama.getText();
        
        int opsi = JOptionPane.showConfirmDialog(null,"Yakin akan menghapus data dari "+NAMA+"("+NIM+")?","Konfirmasi", JOptionPane.YES_NO_OPTION );
        if(opsi == JOptionPane.YES_OPTION){
            String SQLDelete = "DELETE FROM mahasiswa WHERE nim='"+NIM+"';";
            if(this.UpdateData(SQLDelete)){
                this.GetData();
                JOptionPane.showMessageDialog(null, "Data telah dihapus");
            }
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void BtnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddNewActionPerformed
        this.BtnAddNew.setEnabled(false);
        this.BtnUpdate.setEnabled(false);
        this.BtnDelete.setEnabled(false);
        this.BtnClose.setEnabled(false);
        this.BtnSave.setEnabled(true);
        this.BtnCancel.setVisible(true);
        
        this.Fnim.setText("");
        this.Fnama.setText("");
        this.ftgl_lahir.setText("");
        this.Fjurusan.setSelectedIndex(0);
        
        this.LabelDetail.setText("Tambah data Mahasiswa");
        
    }//GEN-LAST:event_BtnAddNewActionPerformed

    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed
        this.BtnClose.setEnabled(true);
        this.BtnAddNew.setEnabled(true);
        this.BtnSave.setEnabled(false);
        this.BtnCancel.setVisible(false);

    }//GEN-LAST:event_BtnCancelActionPerformed

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        String NIM = this.Fnim.getText();
        String NAMA = this.Fnama.getText();
        String TGL = this.ftgl_lahir.getText();
        String JUR = this.Fjurusan.getSelectedItem().toString();
        String JKEL = "L";
        if(this.FjkP.isSelected()){
            JKEL = "P";
        }
        String SQLInsert = "INSERT INTO mahasiswa(nim,nama,jurusan,jk,tanggal_lahir) VALUES('"+NIM+"','"+NAMA+"','"+JUR+"','"+JKEL+"','"+TGL+"');";
        if(this.UpdateData(SQLInsert)){
            this.GetData();
            JOptionPane.showMessageDialog(null, "Data telah di Tambahkan");
        }
        this.BtnSave.setEnabled(false);
        this.BtnCancel.setVisible(false);
        this.BtnClose.setEnabled(true);
        this.BtnAddNew.setEnabled(true);
    }//GEN-LAST:event_BtnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddNew;
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnClose;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnSave;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JRadioButton FjkL;
    private javax.swing.JRadioButton FjkP;
    private javax.swing.JComboBox<String> Fjurusan;
    private javax.swing.JTextField Fnama;
    private javax.swing.JTextField Fnim;
    private javax.swing.JLabel LabelDetail;
    private javax.swing.JTable TabelMahasiswa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField ftgl_lahir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
