package pencatatangui;

public class MainForm extends javax.swing.JFrame {
    DataMhs dm;
    DataDosen dd;
    DataMatkul dmatkul;
    
    public MainForm() {
        this.setSize(1050,530);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskutama = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        MenuExit = new javax.swing.JMenuItem();
        MenuMhs = new javax.swing.JMenu();
        MenuDosen = new javax.swing.JMenu();
        MenuMatkul = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setText("Selamat Datang di Aplikasi Pencatatan");

        dskutama.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dskutamaLayout = new javax.swing.GroupLayout(dskutama);
        dskutama.setLayout(dskutamaLayout);
        dskutamaLayout.setHorizontalGroup(
            dskutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dskutamaLayout.createSequentialGroup()
                .addContainerGap(354, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(316, 316, 316))
        );
        dskutamaLayout.setVerticalGroup(
            dskutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dskutamaLayout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jLabel1)
                .addContainerGap(361, Short.MAX_VALUE))
        );

        getContentPane().add(dskutama, java.awt.BorderLayout.CENTER);

        MenuFile.setText("File");

        MenuExit.setText("Exit");
        MenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExitActionPerformed(evt);
            }
        });
        MenuFile.add(MenuExit);

        jMenuBar1.add(MenuFile);

        MenuMhs.setText("DataMahasiswa");
        MenuMhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMhsMouseClicked(evt);
            }
        });
        MenuMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMhsActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuMhs);

        MenuDosen.setText("DataDosen");
        MenuDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuDosenMouseClicked(evt);
            }
        });
        MenuDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDosenActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuDosen);

        MenuMatkul.setText("DataMatakuliah");
        MenuMatkul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMatkulMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuMatkul);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MenuExitActionPerformed

    private void MenuMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMhsActionPerformed
        
    }//GEN-LAST:event_MenuMhsActionPerformed

    private void MenuMhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMhsMouseClicked
        if(dm==null || dm.isClosed() ){
            dm = new DataMhs();
            dskutama.add(dm);
            dm.setLocation(this.getWidth()/2 - dm.getWidth()/2, this.getHeight()/2-dm.getHeight()/2);
            dm.setVisible(true);
            dd.dispose();
            dmatkul.dispose();
        }else{
            dm.setVisible(true);
        }
    }//GEN-LAST:event_MenuMhsMouseClicked

    private void MenuDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDosenActionPerformed
//        
    }//GEN-LAST:event_MenuDosenActionPerformed

    private void MenuDosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuDosenMouseClicked
        if(dd==null || dd.isClosed() ){
            dd = new DataDosen();
            dskutama.add(dd);
            dd.setLocation(this.getWidth()/2 - dd.getWidth()/2, this.getHeight()/2-dd.getHeight()/2);
            dd.setVisible(true);
            dm.dispose();
            dmatkul.dispose();
        }else{
            dd.setVisible(true);
        }
    }//GEN-LAST:event_MenuDosenMouseClicked

    private void MenuMatkulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMatkulMouseClicked
        if(dmatkul==null || dmatkul.isClosed() ){
            dmatkul = new DataMatkul();
            dskutama.add(dmatkul);
            dmatkul.setLocation(this.getWidth()/2 - dmatkul.getWidth()/2, this.getHeight()/2-dmatkul.getHeight()/2);
            dmatkul.setVisible(true);
            dm.dispose();
            dd.dispose();
        }else{
            dmatkul.setVisible(true);
        }
    }//GEN-LAST:event_MenuMatkulMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuDosen;
    private javax.swing.JMenuItem MenuExit;
    private javax.swing.JMenu MenuFile;
    private javax.swing.JMenu MenuMatkul;
    private javax.swing.JMenu MenuMhs;
    private javax.swing.JDesktopPane dskutama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
